---
name: release
on:
  workflow_dispatch:
    inputs:
      publish_to:
        description: 'Where to publish the release to'
        required: true
        default: '"DockerHub", "GHCR"'
        type: string

permissions: {}

jobs:
  release:
    uses: Brownserve-UK/actions/.github/workflows/brownserve-release.yaml@73e2adb47b47bb461e804dd6c0038f5e4e513f89 # v0.1.0
    permissions:
      contents: read
      packages: write
    with:
      repo-name: 'test-web-app'
      publish-to: ${{ inputs.publish_to }}
    secrets:
      app-id: ${{ secrets.BROWNSERVE_CI_APP_ID }}
      app-private-key: ${{ secrets.BROWNSERVE_CI_APP_PRIVATE_KEY }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK_BUILD }}
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
