---
name: release
on:
  workflow_dispatch:
    inputs:
      publish_to:
        description: 'Where to publish the release to'
        required: true
        default: '"GitHub"'
        type: string

permissions: {}

jobs:
  release:
    uses: Brownserve-UK/actions/.github/workflows/brownserve-release.yaml@73e2adb47b47bb461e804dd6c0038f5e4e513f89 # v0.1.0
    permissions:
      contents: read
      packages: write
    with:
      repo-name: 'test-skills-repo'
      publish-to: ${{ inputs.publish_to }}
    secrets:
      app-id: ${{ secrets.BROWNSERVE_CI_APP_ID }}
      app-private-key: ${{ secrets.BROWNSERVE_CI_APP_PRIVATE_KEY }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK_BUILD }}

  deploy-docs:
    needs: release
    uses: Brownserve-UK/actions/.github/workflows/brownserve-deploy-docs.yaml@73e2adb47b47bb461e804dd6c0038f5e4e513f89 # v0.1.0
    permissions:
      contents: write
    with:
      engine: astro
      docs-path: pages
