---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "Brownserve-UK/actions*"

  - package-ecosystem: nuget
    directory: /.config
    schedule:
      interval: weekly
