---
name: label-pr
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - labeled
      - unlabeled
    branches:
      - main

permissions: {}

jobs:
  label-pr:
    uses: Brownserve-UK/actions/.github/workflows/brownserve-label-pr.yaml@73e2adb47b47bb461e804dd6c0038f5e4e513f89 # v0.1.0
    permissions:
      issues: write
      pull-requests: write
