---
name: stage-release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'The type of release to perform'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

permissions: {}

jobs:
  stage-release:
    uses: Brownserve-UK/actions/.github/workflows/brownserve-stage-release.yaml@28d69596e4bcf98b0fe7f260c8ea2486265cd03a # v0.2.0
    permissions:
      contents: read
    with:
      repo-name: 'test-rust-app'
      release-type: ${{ inputs.release_type }}
      rust: true
    secrets:
      app-id: ${{ secrets.BROWNSERVE_CI_APP_ID }}
      app-private-key: ${{ secrets.BROWNSERVE_CI_APP_PRIVATE_KEY }}
