---
name: stage-release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'The type of release to perform'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

permissions: {}

jobs:
  stage-release:
    uses: Brownserve-UK/actions/.github/workflows/brownserve-stage-release.yaml@73e2adb47b47bb461e804dd6c0038f5e4e513f89 # v0.1.0
    permissions:
      contents: read
    with:
      repo-name: 'test-rust-app'
      release-type: ${{ inputs.release_type }}
      rust: true
    secrets:
      app-id: ${{ secrets.BROWNSERVE_CI_APP_ID }}
      app-private-key: ${{ secrets.BROWNSERVE_CI_APP_PRIVATE_KEY }}
